user: rails
pid: tmp/pids/thin.pid
timeout: 600
#wait: 30
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
rackup: config.ru
servers: 4
#threaded: true
no-epoll: true
daemonize: true
#socket: tmp/sockets/thin.sock
port: 3300
chdir: /srv/www/application_name/current